### ISSUE TITLE
 No prebuilt binaries found (target=4.2.7 runtime=node arch=x64 libc= platform=win32)

### ISSUE THREAD

**Issue by UziTech** [oznu/node-pty-prebuilt-multiarch#7] opened 2019-08-13 23:17 UTC
## Environment details

- OS: Windows 10
- OS version: x64
- node-pty version: 0.9.0-beta21.legacy

## Issue description

Trying to use platformio-ide-terminal on Atom v1.41.0-beta0

No prebuilt binaries found (target=4.2.7 runtime=node arch=x64 libc= platform=win32)

related https://github.com/platformio/platformio-atom-ide-terminal/issues/766

**Comment by the-j0k3r** [comment] 2019-08-14 17:36
I can confirm from two independent sources that macOS and Linux and flavours work fine, its just Windows binaries that seem to be affected. I need to test locally other tags to see if I can narrow this down.

I know this is very likely unrelated but I have submitted [a PR to fix the Windows builds completion](https://github.com/oznu/node-pty-prebuilt-multiarch/pull/6). Ive no idea if that has any bearing on issue.

I also found it odd that electron 3.x and 4.0 have same ABI 64

https://github.com/lgeiger/node-abi/blob/3651a264d7ba540689ae469ed88c075dc340c188/index.js#L69-L70 but since it works in Linux/macOS its definitely not it.

**Comment by the-j0k3r** [comment] 2019-08-17 06:53
ping

**Comment by the-j0k3r** [comment] 2019-08-17 16:58
@UziTech see https://github.com/atom/atom/issues/19780

**Comment by the-j0k3r** [comment] 2019-08-21 04:56
I think its safe to close this issue.

**Closed** 2019-08-21 12:17 UTC
